// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(95472a3b-86b6-454c-9a32-b6ba4399486f),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

